// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IJoinSystem {
  function join(address _user) external returns (uint8 playerId_);
}
