// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IMapSystem {
  function add(uint32 _x, uint32 _y, uint8 _id) external;

  function calculate() external;
}
